--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/denis/wallpaper/stairs.jpg"

-- Special
background="#030303"
foreground="#a0a0a0"
cursor="#a0a0a0"

-- Colors
color0="#030303"
color1="#4c4c4c"
color2="#5c5c5c"
color3="#7c7c7c"
color4="#949494"
color5="#a8a8a8"
color6="#bcbcbc"
color7="#a0a0a0"
color8="#414141"
color9="#4c4c4c"
color10="#5c5c5c"
color11="#7c7c7c"
color12="#949494"
color13="#a8a8a8"
color14="#bcbcbc"
color15="#a0a0a0"
