# Shell variables
# Generated by 'wal'
wallpaper='/home/denis/wallpaper/stairs.jpg'

# Special
background='#030303'
foreground='#a0a0a0'
cursor='#a0a0a0'

# Colors
color0='#030303'
color1='#4c4c4c'
color2='#5c5c5c'
color3='#7c7c7c'
color4='#949494'
color5='#a8a8a8'
color6='#bcbcbc'
color7='#a0a0a0'
color8='#414141'
color9='#4c4c4c'
color10='#5c5c5c'
color11='#7c7c7c'
color12='#949494'
color13='#a8a8a8'
color14='#bcbcbc'
color15='#a0a0a0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
